version: '3'
services:
  database:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hedgedoc
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
  app:
    # Make sure to use the latest release from https://hedgedoc.org/latest-release
    image: quay.io/hedgedoc/hedgedoc:1.9.9
    environment:
      - CMD_DB_URL=postgres://hedgedoc:password@database:5432/hedgedoc
      - CMD_DOMAIN=localhost
      - CMD_URL_ADDPORT=true
      - CMD_SAML_ISSUER=hedgedoc
      - CMD_SAML_IDPSSOURL=http://localhost:8080/realms/hedgedoc/protocol/saml
      - CMD_SAML_IDENTIFIERFORMAT=urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
      - CMD_SAML_IDPCERT=/hedgedoc/idpCert/idpCert.pem
      - CMD_SAML_ATTRIBUTE_USERNAME=username
      - CMD_SAML_ATTRIBUTE_EMAIL=email
    volumes:
      - uploads:/hedgedoc/public/uploads
      - .:/hedgedoc/idpCert
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - database
volumes:
  database:
  uploads:
